version: '3'

volumes:
    db_dev: {}

services:
    db:
        platform: linux/x86_64
        container_name: dlabon-mysql
        image: mysql:5.7
        volumes:
            - db_dev:/var/lib/mysql
        ports:
            - 3306:3306
        environment: 
            - MYSQL_DATABASE=dlabon
            - MYSQL_USER=dlabon
            - MYSQL_PASSWORD=!db_dev#
            - MYSQL_ROOT_PASSWORD=!db_dev#

    web:
        container_name: dlabon-web
        build:
            context: .
            dockerfile: ./docker/Dockerfile-dev-web
        volumes:
            - .:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - db