FROM php:7.4-apache

# install php ext modules
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libzip-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install zip \
    && rm -rf /tmp/* \
    && rm -rf /var/list/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# apache2 rewrite module enable
RUN a2enmod rewrite

# disable default site and delete all default files
RUN a2dissite 000-default.conf
RUN rm -r /var/www/html

# create dlabon site
COPY ./docker/dlabon.conf /etc/apache2/sites-available/dlabon.conf
RUN a2ensite dlabon.conf
RUN service apache2 restart

# php.ini
COPY ./docker/php.ini "$PHP_INI_DIR/php.ini"
